import { AccountProfile, AuditAccount } from '@/types';

export const INITIAL_DEMO_PROFILE: AccountProfile = {
  handle: 'Grindoors_xyz',
  name: 'Grindoors Community',
  avatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
  verified: true,
  postsCount: 1420,
  repliesCount: 3840,
  repostsCount: 650,
  followingCount: 991,
  followersCount: 12400,
  joinedDate: 'March 2022',
  bio: 'Building Web3 tools & community experiments. Autonomous automation enthusiast.',
};

export const INITIAL_AUDIT_ACCOUNTS: AuditAccount[] = [
  {
    id: '1',
    handle: 'elonmusk',
    name: 'Elon Musk',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    isDefaultAvatar: false,
    isFollowingBack: false,
    followingCount: 780,
    followersCount: 195000000,
    bio: '',
    botRiskScore: 10,
    riskFlags: ['Non-Mutual'],
    isWhitelisted: true,
  },
  {
    id: '2',
    handle: 'AlexTrader98314',
    name: 'Alex || Sol Alpha',
    avatarUrl: '',
    isDefaultAvatar: true,
    isFollowingBack: false,
    followingCount: 4890,
    followersCount: 14,
    bio: 'DM for signals 🚀 Free solana call channel link in bio #crypto',
    botRiskScore: 92,
    riskFlags: ['Default Avatar', 'Random Digits (@AlexTrader98314)', 'Extreme Follow Ratio (4890:14)', 'Non-Mutual'],
    isWhitelisted: false,
  },
  {
    id: '3',
    handle: 'CryptoBot_8812',
    name: 'Auto Yield Bot',
    avatarUrl: '',
    isDefaultAvatar: true,
    isFollowingBack: false,
    followingCount: 7200,
    followersCount: 3,
    bio: '',
    botRiskScore: 98,
    riskFlags: ['Default Avatar', 'Empty Bio', 'Random Digits', 'Extreme Follow Ratio (7200:3)', 'Non-Mutual'],
    isWhitelisted: false,
  },
  {
    id: '4',
    handle: 'sama',
    name: 'Sam Altman',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isDefaultAvatar: false,
    isFollowingBack: false,
    followingCount: 650,
    followersCount: 3200000,
    bio: '',
    botRiskScore: 15,
    riskFlags: ['Non-Mutual'],
    isWhitelisted: true,
  },
  {
    id: '5',
    handle: 'john_dev_29381',
    name: 'John Developer',
    avatarUrl: '',
    isDefaultAvatar: true,
    isFollowingBack: false,
    followingCount: 3410,
    followersCount: 42,
    bio: 'Looking for airdrops 2026',
    botRiskScore: 84,
    riskFlags: ['Default Avatar', 'Random Digits', 'Non-Mutual'],
    isWhitelisted: false,
  },
  {
    id: '6',
    handle: 'vaboris_ai',
    name: 'Vitalik Buterin',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isDefaultAvatar: false,
    isFollowingBack: true,
    followingCount: 420,
    followersCount: 5400000,
    bio: 'Ethereum researcher',
    botRiskScore: 5,
    riskFlags: [],
    isWhitelisted: true,
  },
  {
    id: '7',
    handle: 'airdrop_hunter_9999',
    name: 'AIRDROP NOTIFIER',
    avatarUrl: '',
    isDefaultAvatar: true,
    isFollowingBack: false,
    followingCount: 5000,
    followersCount: 1,
    bio: '',
    botRiskScore: 99,
    riskFlags: ['Default Avatar', 'Empty Bio', 'Extreme Follow Ratio (5000:1)', 'Non-Mutual'],
    isWhitelisted: false,
  },
  {
    id: '8',
    handle: 'sarah_designer',
    name: 'Sarah Chen',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    isDefaultAvatar: false,
    isFollowingBack: true,
    followingCount: 310,
    followersCount: 1200,
    bio: 'Product Designer @ Web3. Coffee and CSS.',
    botRiskScore: 0,
    riskFlags: [],
    isWhitelisted: false,
  },
];
